apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground-argo-application
  namespace: argocd
  labels:                                   
    app: wil-playground
  annotations:
    owner: "mpeulet"
spec:
  project: default

  source:
    repoURL: https://github.com/MaloP47/IOT-mpeulet.git
    targetRevision: HEAD
    path: dev
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Validate=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
