apiVersion: v2
kind: Service
metadata:
  name: svc-wil-playground
  namespace: dev
  labels:
    app: svc-wil-playground
spec:
  selector:
    app: wil-playground
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 8888
  type: ClusterIP
